// QID-canonical SubjectConcepts - run after migrate_subject_concepts_to_qid_canonical.cypher
// Generated by load_subject_concepts_qid_canonical.py --cypher

MERGE (kd:KnowledgeDomain {qid: 'Q17167'})
SET kd.label = 'Roman Republic';

MERGE (sc:SubjectConcept {qid: 'Q104867898'})
SET sc.subject_id = 'Q104867898', sc.label = 'Marriage alliances and political kinship', sc.primary_facet = 'BIOGRAPHIC', sc.confidence = 'llm:0.85', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q105427'})
SET sc.subject_id = 'Q105427', sc.label = 'Institutions: Senate, Assemblies, Magistracies', sc.primary_facet = 'POLITICAL', sc.confidence = 'curated', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q11019'})
SET sc.subject_id = 'Q11019', sc.label = 'Trade routes and maritime networks', sc.primary_facet = 'ECONOMIC', sc.confidence = 'llm:0.85', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q11469'})
SET sc.subject_id = 'Q11469', sc.label = 'Landholding, Agriculture, and Estates', sc.primary_facet = 'ECONOMIC', sc.confidence = 'curated', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q1200427'})
SET sc.subject_id = 'Q1200427', sc.label = 'Culture, Ideas, and Communication', sc.primary_facet = 'CULTURAL', sc.confidence = 'llm:0.90', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q1234567'})
SET sc.subject_id = 'Q1234567', sc.label = 'Finance, contracts, and publicani', sc.primary_facet = 'ECONOMIC', sc.confidence = 'llm:0.95', sc.source = 'wikidata', sc.harvest_status = 'unconfirmed';

MERGE (sc:SubjectConcept {qid: 'Q1243998'})
SET sc.subject_id = 'Q1243998', sc.label = 'Battles and Operations', sc.primary_facet = 'MILITARY', sc.confidence = 'llm:0.95', sc.source = 'wikidata', sc.harvest_status = 'unconfirmed';

MERGE (sc:SubjectConcept {qid: 'Q131416'})
SET sc.subject_id = 'Q131416', sc.label = 'Priesthoods and sacred colleges', sc.primary_facet = 'RELIGIOUS', sc.confidence = 'llm:0.95', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q1363254'})
SET sc.subject_id = 'Q1363254', sc.label = 'Land reform, redistribution, agrarian policy', sc.primary_facet = 'ECONOMIC', sc.confidence = 'curated', sc.source = 'wikidata', sc.harvest_status = 'unconfirmed';

MERGE (sc:SubjectConcept {qid: 'Q1367629'})
SET sc.subject_id = 'Q1367629', sc.label = 'Ritual Practice, Omens, and Public Ceremony', sc.primary_facet = 'RELIGIOUS', sc.confidence = 'llm:0.95', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q1392538'})
SET sc.subject_id = 'Q1392538', sc.label = 'Society and Social Structure', sc.primary_facet = 'SOCIAL', sc.confidence = 'llm:0.95', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q15265460'})
SET sc.subject_id = 'Q15265460', sc.label = 'Economy and Resource Systems', sc.primary_facet = 'ECONOMIC', sc.confidence = 'llm:0.85', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q1541'})
SET sc.subject_id = 'Q1541', sc.label = 'Forums, public speech, persuasion', sc.primary_facet = 'COMMUNICATION', sc.confidence = 'llm:0.95', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q15800869'})
SET sc.subject_id = 'Q15800869', sc.label = 'Early Republic (periodization)', sc.primary_facet = 'TEMPORAL', sc.confidence = 'llm:0.95', sc.source = 'wikidata', sc.harvest_status = 'unconfirmed';

MERGE (sc:SubjectConcept {qid: 'Q1593880'})
SET sc.subject_id = 'Q1593880', sc.label = 'Institutions of slavery and manumission', sc.primary_facet = 'SOCIAL', sc.confidence = 'llm:0.95', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q17167'})
SET sc.subject_id = 'Q17167', sc.label = 'Roman Republic', sc.primary_facet = 'POLITICAL', sc.confidence = 'root', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q172845'})
SET sc.subject_id = 'Q172845', sc.label = 'Religion and Public Cult', sc.primary_facet = 'RELIGIOUS', sc.confidence = 'llm:0.95', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q1747183'})
SET sc.subject_id = 'Q1747183', sc.label = 'Internal wars (civil/social/rebellion)', sc.primary_facet = 'MILITARY', sc.confidence = 'llm:0.90', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q1764124'})
SET sc.subject_id = 'Q1764124', sc.label = 'External wars (interstate/expansionary)', sc.primary_facet = 'MILITARY', sc.confidence = 'llm:0.85', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q1812526'})
SET sc.subject_id = 'Q1812526', sc.label = 'Reforms and constitutional change', sc.primary_facet = 'POLITICAL', sc.confidence = 'llm:0.75', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q182547'})
SET sc.subject_id = 'Q182547', sc.label = 'Provinces and Administration', sc.primary_facet = 'GEOGRAPHIC', sc.confidence = 'llm:1.00', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q185816'})
SET sc.subject_id = 'Q185816', sc.label = 'Naval warfare and sea operations', sc.primary_facet = 'MILITARY', sc.confidence = 'curated', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q186916'})
SET sc.subject_id = 'Q186916', sc.label = 'Chronology and Periodization', sc.primary_facet = 'TEMPORAL', sc.confidence = 'llm:0.95', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q1944199'})
SET sc.subject_id = 'Q1944199', sc.label = 'Mechanisms of patronage', sc.primary_facet = 'SOCIAL', sc.confidence = 'llm:1.00', sc.source = 'wikidata', sc.harvest_status = 'unconfirmed';

MERGE (sc:SubjectConcept {qid: 'Q19895241'})
SET sc.subject_id = 'Q19895241', sc.label = 'Symbols, memory, persuasive narratives', sc.primary_facet = 'COMMUNICATION', sc.confidence = 'llm:0.85', sc.source = 'wikidata', sc.harvest_status = 'unconfirmed';

MERGE (sc:SubjectConcept {qid: 'Q1993655'})
SET sc.subject_id = 'Q1993655', sc.label = 'Civil wars and internal conflicts', sc.primary_facet = 'POLITICAL', sc.confidence = 'curated', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q201452'})
SET sc.subject_id = 'Q201452', sc.label = 'Diplomacy and International Relations', sc.primary_facet = 'DIPLOMATIC', sc.confidence = 'llm:0.85', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q2063299'})
SET sc.subject_id = 'Q2063299', sc.label = 'Elite competition and network power', sc.primary_facet = 'SOCIAL', sc.confidence = 'llm:0.90', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q2065169'})
SET sc.subject_id = 'Q2065169', sc.label = 'Political violence, proscriptions, purges', sc.primary_facet = 'POLITICAL', sc.confidence = 'llm:0.90', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q2067204'})
SET sc.subject_id = 'Q2067204', sc.label = 'Oratory, Rhetoric, and Propaganda', sc.primary_facet = 'COMMUNICATION', sc.confidence = 'llm:0.95', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q2067294'})
SET sc.subject_id = 'Q2067294', sc.label = 'Republican ideals (virtus, mos maiorum, liberty)', sc.primary_facet = 'INTELLECTUAL', sc.confidence = 'llm:0.95', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q20720797'})
SET sc.subject_id = 'Q20720797', sc.label = 'Factions, Patronage Power, and Civil Conflict', sc.primary_facet = 'POLITICAL', sc.confidence = 'llm:0.95', sc.source = 'wikidata', sc.harvest_status = 'unconfirmed';

MERGE (sc:SubjectConcept {qid: 'Q207544'})
SET sc.subject_id = 'Q207544', sc.label = 'Geography, Provinces, and Expansion', sc.primary_facet = 'GEOGRAPHIC', sc.confidence = 'llm:0.95', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q207640'})
SET sc.subject_id = 'Q207640', sc.label = 'Public ritual, auspices, legitimacy', sc.primary_facet = 'RELIGIOUS', sc.confidence = 'llm:0.95', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q211364'})
SET sc.subject_id = 'Q211364', sc.label = 'Popular/admin offices: Tribune, Aedile, Quaestor', sc.primary_facet = 'POLITICAL', sc.confidence = 'llm:0.85', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q212943'})
SET sc.subject_id = 'Q212943', sc.label = 'Religious Offices, Priesthoods, and Authority', sc.primary_facet = 'RELIGIOUS', sc.confidence = 'llm:0.95', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q213810'})
SET sc.subject_id = 'Q213810', sc.label = 'Law, Citizenship, and Constitutional Practice', sc.primary_facet = 'POLITICAL', sc.confidence = 'llm:0.95', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q2277'})
SET sc.subject_id = 'Q2277', sc.label = 'Transition to Empire', sc.primary_facet = 'TEMPORAL', sc.confidence = 'llm:0.90', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q2345364'})
SET sc.subject_id = 'Q2345364', sc.label = 'Historiography, Sources, and Historical Method', sc.primary_facet = 'INTELLECTUAL', sc.confidence = 'llm:0.95', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q236885'})
SET sc.subject_id = 'Q236885', sc.label = 'Dictatorship & extraordinary commands', sc.primary_facet = 'POLITICAL', sc.confidence = 'llm:1.00', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q2576746'})
SET sc.subject_id = 'Q2576746', sc.label = 'Constitutionalism and mixed government models', sc.primary_facet = 'INTELLECTUAL', sc.confidence = 'llm:0.95', sc.source = 'wikidata', sc.harvest_status = 'unconfirmed';

MERGE (sc:SubjectConcept {qid: 'Q271108'})
SET sc.subject_id = 'Q271108', sc.label = 'Factional politics (Optimates/Populares framing)', sc.primary_facet = 'POLITICAL', sc.confidence = 'llm:0.85', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q2817119'})
SET sc.subject_id = 'Q2817119', sc.label = 'Envoys, embassies, negotiation practice', sc.primary_facet = 'DIPLOMATIC', sc.confidence = 'llm:0.85', sc.source = 'wikidata', sc.harvest_status = 'unconfirmed';

MERGE (sc:SubjectConcept {qid: 'Q2862991'})
SET sc.subject_id = 'Q2862991', sc.label = 'Warfare and Military Systems', sc.primary_facet = 'MILITARY', sc.confidence = 'llm:0.95', sc.source = 'wikidata', sc.harvest_status = 'unconfirmed';

MERGE (sc:SubjectConcept {qid: 'Q2916317'})
SET sc.subject_id = 'Q2916317', sc.label = 'Military roles & command structure', sc.primary_facet = 'MILITARY', sc.confidence = 'llm:0.95', sc.source = 'wikidata', sc.harvest_status = 'unconfirmed';

MERGE (sc:SubjectConcept {qid: 'Q3277005'})
SET sc.subject_id = 'Q3277005', sc.label = 'Magistracies (powers, term limits, imperium)', sc.primary_facet = 'POLITICAL', sc.confidence = 'llm:0.95', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q3932035'})
SET sc.subject_id = 'Q3932035', sc.label = 'Client Kingdoms, Alliances, and Hegemony', sc.primary_facet = 'DIPLOMATIC', sc.confidence = 'llm:0.95', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q3952'})
SET sc.subject_id = 'Q3952', sc.label = 'Late Republic (periodization)', sc.primary_facet = 'TEMPORAL', sc.confidence = 'llm:0.95', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q39686'})
SET sc.subject_id = 'Q39686', sc.label = 'Offices and Magistracies (Cursus Honorum)', sc.primary_facet = 'POLITICAL', sc.confidence = 'curated', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q4119583'})
SET sc.subject_id = 'Q4119583', sc.label = 'Treaties, Negotiations, and Envoys', sc.primary_facet = 'DIPLOMATIC', sc.confidence = 'llm:0.85', sc.source = 'wikidata', sc.harvest_status = 'unconfirmed';

MERGE (sc:SubjectConcept {qid: 'Q46303'})
SET sc.subject_id = 'Q46303', sc.label = 'Wars and Campaigns', sc.primary_facet = 'MILITARY', sc.confidence = 'curated', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q6106068'})
SET sc.subject_id = 'Q6106068', sc.label = 'Middle Republic (periodization)', sc.primary_facet = 'TEMPORAL', sc.confidence = 'llm:1.00', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q657326'})
SET sc.subject_id = 'Q657326', sc.label = 'Social orders (Patrician, Plebeian, Equites)', sc.primary_facet = 'SOCIAL', sc.confidence = 'llm:0.85', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q726929'})
SET sc.subject_id = 'Q726929', sc.label = 'Courts, trials, legal procedure', sc.primary_facet = 'POLITICAL', sc.confidence = 'llm:0.95', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q838930'})
SET sc.subject_id = 'Q838930', sc.label = 'Rome and Italy (Republic Context)', sc.primary_facet = 'GEOGRAPHIC', sc.confidence = 'llm:1.00', sc.source = 'wikidata', sc.harvest_status = 'unconfirmed';

MERGE (sc:SubjectConcept {qid: 'Q8434'})
SET sc.subject_id = 'Q8434', sc.label = 'Government and Constitutional Structure', sc.primary_facet = 'POLITICAL', sc.confidence = 'llm:0.95', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q8464'})
SET sc.subject_id = 'Q8464', sc.label = 'Slavery, Labor, and Dependency', sc.primary_facet = 'SOCIAL', sc.confidence = 'curated', sc.source = 'wikidata', sc.harvest_status = 'unconfirmed';

MERGE (sc:SubjectConcept {qid: 'Q859980'})
SET sc.subject_id = 'Q859980', sc.label = 'Popular assemblies and voting', sc.primary_facet = 'POLITICAL', sc.confidence = 'curated', sc.source = 'wikidata', sc.harvest_status = 'unconfirmed';

MERGE (sc:SubjectConcept {qid: 'Q899409'})
SET sc.subject_id = 'Q899409', sc.label = 'Families, Gentes, and Prosopography', sc.primary_facet = 'BIOGRAPHIC', sc.confidence = 'llm:1.00', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MERGE (sc:SubjectConcept {qid: 'Q9070'})
SET sc.subject_id = 'Q9070', sc.label = 'Civic Culture, Identity, and Romanitas', sc.primary_facet = 'CULTURAL', sc.confidence = 'llm:1.00', sc.source = 'wikidata', sc.harvest_status = 'unconfirmed';

MERGE (sc:SubjectConcept {qid: 'Q952064'})
SET sc.subject_id = 'Q952064', sc.label = 'Markets, money, and exchange', sc.primary_facet = 'ECONOMIC', sc.confidence = 'llm:0.95', sc.source = 'wikidata', sc.harvest_status = 'confirmed';

MATCH (sc:SubjectConcept {qid: 'Q104867898'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q105427'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q11019'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q11469'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q1200427'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q1234567'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q1243998'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q131416'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q1363254'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q1367629'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q1392538'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q15265460'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q1541'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q15800869'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q1593880'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q17167'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q172845'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q1747183'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q1764124'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q1812526'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q182547'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q185816'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q186916'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q1944199'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q19895241'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q1993655'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q201452'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q2063299'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q2065169'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q2067204'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q2067294'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q20720797'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q207544'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q207640'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q211364'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q212943'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q213810'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q2277'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q2345364'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q236885'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q2576746'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q271108'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q2817119'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q2862991'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q2916317'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q3277005'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q3932035'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q3952'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q39686'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q4119583'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q46303'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q6106068'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q657326'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q726929'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q838930'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q8434'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q8464'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q859980'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q899409'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q9070'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (sc:SubjectConcept {qid: 'Q952064'})
MATCH (kd:KnowledgeDomain {qid: 'Q17167'})
MERGE (sc)-[:DOMAIN_OF]->(kd);

MATCH (broader:SubjectConcept {qid: 'Q17167'})
MATCH (narrower:SubjectConcept {qid: 'Q8434'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q17167'})
MATCH (narrower:SubjectConcept {qid: 'Q2862991'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q17167'})
MATCH (narrower:SubjectConcept {qid: 'Q1392538'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q17167'})
MATCH (narrower:SubjectConcept {qid: 'Q15265460'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q17167'})
MATCH (narrower:SubjectConcept {qid: 'Q207544'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q17167'})
MATCH (narrower:SubjectConcept {qid: 'Q201452'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q17167'})
MATCH (narrower:SubjectConcept {qid: 'Q172845'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q17167'})
MATCH (narrower:SubjectConcept {qid: 'Q1200427'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q17167'})
MATCH (narrower:SubjectConcept {qid: 'Q186916'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q8434'})
MATCH (narrower:SubjectConcept {qid: 'Q105427'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q8434'})
MATCH (narrower:SubjectConcept {qid: 'Q39686'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q8434'})
MATCH (narrower:SubjectConcept {qid: 'Q213810'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q8434'})
MATCH (narrower:SubjectConcept {qid: 'Q20720797'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q105427'})
MATCH (narrower:SubjectConcept {qid: 'Q859980'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q105427'})
MATCH (narrower:SubjectConcept {qid: 'Q3277005'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q39686'})
MATCH (narrower:SubjectConcept {qid: 'Q211364'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q39686'})
MATCH (narrower:SubjectConcept {qid: 'Q236885'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q213810'})
MATCH (narrower:SubjectConcept {qid: 'Q726929'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q213810'})
MATCH (narrower:SubjectConcept {qid: 'Q1812526'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q20720797'})
MATCH (narrower:SubjectConcept {qid: 'Q271108'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q20720797'})
MATCH (narrower:SubjectConcept {qid: 'Q1993655'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q20720797'})
MATCH (narrower:SubjectConcept {qid: 'Q2065169'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q2862991'})
MATCH (narrower:SubjectConcept {qid: 'Q46303'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q2862991'})
MATCH (narrower:SubjectConcept {qid: 'Q1243998'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q46303'})
MATCH (narrower:SubjectConcept {qid: 'Q1764124'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q46303'})
MATCH (narrower:SubjectConcept {qid: 'Q1747183'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q1243998'})
MATCH (narrower:SubjectConcept {qid: 'Q185816'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q1392538'})
MATCH (narrower:SubjectConcept {qid: 'Q1993655'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q1392538'})
MATCH (narrower:SubjectConcept {qid: 'Q899409'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q1392538'})
MATCH (narrower:SubjectConcept {qid: 'Q8464'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q1392538'})
MATCH (narrower:SubjectConcept {qid: 'Q657326'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q1392538'})
MATCH (narrower:SubjectConcept {qid: 'Q213810'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q1993655'})
MATCH (narrower:SubjectConcept {qid: 'Q1944199'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q1993655'})
MATCH (narrower:SubjectConcept {qid: 'Q2063299'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q899409'})
MATCH (narrower:SubjectConcept {qid: 'Q104867898'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q8464'})
MATCH (narrower:SubjectConcept {qid: 'Q1593880'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q8464'})
MATCH (narrower:SubjectConcept {qid: 'Q1593880'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q15265460'})
MATCH (narrower:SubjectConcept {qid: 'Q11469'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q11469'})
MATCH (narrower:SubjectConcept {qid: 'Q1363254'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q17167'})
MATCH (narrower:SubjectConcept {qid: 'Q1234567'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q207544'})
MATCH (narrower:SubjectConcept {qid: 'Q838930'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q207544'})
MATCH (narrower:SubjectConcept {qid: 'Q182547'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q201452'})
MATCH (narrower:SubjectConcept {qid: 'Q4119583'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q201452'})
MATCH (narrower:SubjectConcept {qid: 'Q3932035'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q4119583'})
MATCH (narrower:SubjectConcept {qid: 'Q2817119'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q172845'})
MATCH (narrower:SubjectConcept {qid: 'Q212943'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q172845'})
MATCH (narrower:SubjectConcept {qid: 'Q1367629'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q212943'})
MATCH (narrower:SubjectConcept {qid: 'Q131416'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q1367629'})
MATCH (narrower:SubjectConcept {qid: 'Q207640'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q1200427'})
MATCH (narrower:SubjectConcept {qid: 'Q2067204'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q1200427'})
MATCH (narrower:SubjectConcept {qid: 'Q2345364'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q1200427'})
MATCH (narrower:SubjectConcept {qid: 'Q9070'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q2067204'})
MATCH (narrower:SubjectConcept {qid: 'Q1541'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q2067204'})
MATCH (narrower:SubjectConcept {qid: 'Q19895241'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q17167'})
MATCH (narrower:SubjectConcept {qid: 'Q2067294'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q17167'})
MATCH (narrower:SubjectConcept {qid: 'Q2576746'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q186916'})
MATCH (narrower:SubjectConcept {qid: 'Q15800869'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q186916'})
MATCH (narrower:SubjectConcept {qid: 'Q6106068'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q186916'})
MATCH (narrower:SubjectConcept {qid: 'Q3952'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q186916'})
MATCH (narrower:SubjectConcept {qid: 'Q2277'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

MATCH (broader:SubjectConcept {qid: 'Q3952'})
MATCH (narrower:SubjectConcept {qid: 'Q1993655'})
MERGE (broader)-[:BROADER_THAN]->(narrower);

