MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q109386511>'}) SET p.label = 'Early Dynastic III' SET p.start_year = 2599 SET p.end_year = 2339 MERGE (start:Year {value: 2599}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 2339}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:ArchaeologicalFacet:Facet {unique_id: 'ARCHAEOLOGICALFACET_ARCHAEOLOGICAL'}) SET f.label = 'archaeological' MERGE (p)-[:HAS_ARCHAEOLOGICAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q11767>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q110209550>'}) SET p.label = 'Early Dynastic IIIa' SET p.start_year = 2599 SET p.end_year = 2499 MERGE (start:Year {value: 2599}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 2499}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:ArchaeologicalFacet:Facet {unique_id: 'ARCHAEOLOGICALFACET_ARCHAEOLOGICAL'}) SET f.label = 'archaeological' MERGE (p)-[:HAS_ARCHAEOLOGICAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q11767>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q110209565>'}) SET p.label = 'Early Dynastic IIIb' SET p.start_year = 2499 SET p.end_year = 2339 MERGE (start:Year {value: 2499}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 2339}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:ArchaeologicalFacet:Facet {unique_id: 'ARCHAEOLOGICALFACET_ARCHAEOLOGICAL'}) SET f.label = 'archaeological' MERGE (p)-[:HAS_ARCHAEOLOGICAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q11767>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q1196237>'}) SET p.label = 'Proto-Elamite period' SET p.start_year = 3099 SET p.end_year = 2699 MERGE (start:Year {value: 3099}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 2699}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:ArchaeologicalFacet:Facet {unique_id: 'ARCHAEOLOGICALFACET_ARCHAEOLOGICAL'}) SET f.label = 'archaeological' MERGE (p)-[:HAS_ARCHAEOLOGICAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q128904>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q1201263>'}) SET p.label = 'Warlord Era' SET p.start_year = 1916 SET p.end_year = 1928 MERGE (start:Year {value: 1916}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1928}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q29520>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q12554>'}) SET p.label = 'Middle Ages' SET p.start_year = 476 SET p.end_year = 1500 MERGE (start:Year {value: 476}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1500}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q46>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q129167>'}) SET p.label = 'barracks emperor' SET p.start_year = 235 SET p.end_year = 284 MERGE (start:Year {value: 235}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 284}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q2277>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q131192>'}) SET p.label = 'Migration Period' SET p.start_year = 375 SET p.end_year = 568 MERGE (start:Year {value: 375}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 568}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q466039>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q134178>'}) SET p.label = 'Minoan civilization' SET p.start_year = 2000 SET p.end_year = 1099 MERGE (start:Year {value: 2000}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1099}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:ArchaeologicalFacet:Facet {unique_id: 'ARCHAEOLOGICALFACET_ARCHAEOLOGICAL'}) SET f.label = 'archaeological' MERGE (p)-[:HAS_ARCHAEOLOGICAL_FACET]->(f) MERGE (f1:ArtisticFacet:Facet {unique_id: 'ARTISTICFACET_ARTISTIC'}) SET f1.label = 'artistic' MERGE (p)-[:HAS_ARTISTIC_FACET]->(f1) MERGE (f2:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f2.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f2) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q34374>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q13577667>'}) SET p.label = 'Isin-Larsa period' SET p.start_year = 1999 SET p.end_year = 1799 MERGE (start:Year {value: 1999}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1799}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q11767>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q1376093>'}) SET p.label = 'Samhan' SET p.start_year = 150 SET p.end_year = 236 MERGE (start:Year {value: 150}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 236}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q18097>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q1474884>'}) SET p.label = 'High Renaissance' SET p.start_year = 1494 SET p.end_year = 1527 MERGE (start:Year {value: 1494}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1527}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:ArtisticFacet:Facet {unique_id: 'ARTISTICFACET_ARTISTIC'}) SET f.label = 'artistic' MERGE (p)-[:HAS_ARTISTIC_FACET]->(f) MERGE (f1:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f1.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f1) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q38>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q1543663>'}) SET p.label = 'Sultanate of Women' SET p.start_year = 1520 SET p.end_year = 1648 MERGE (start:Year {value: 1520}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1648}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q12560>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q202390>'}) SET p.label = 'pre-Columbian era' SET p.start_year = 48000 SET p.end_year = 1492 MERGE (start:Year {value: 48000}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1492}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:ArchaeologicalFacet:Facet {unique_id: 'ARCHAEOLOGICALFACET_ARCHAEOLOGICAL'}) SET f.label = 'archaeological' MERGE (p)-[:HAS_ARCHAEOLOGICAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q828>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q937774>'}) SET p.label = 'Helladic period' SET p.start_year = 2999 SET p.end_year = 1099 MERGE (start:Year {value: 2999}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1099}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:ArchaeologicalFacet:Facet {unique_id: 'ARCHAEOLOGICALFACET_ARCHAEOLOGICAL'}) SET f.label = 'archaeological' MERGE (p)-[:HAS_ARCHAEOLOGICAL_FACET]->(f) MERGE (f1:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f1.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f1) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q78967>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q109384761>'}) SET p.label = 'Ur III period' SET p.start_year = 2099 SET p.end_year = 1999 MERGE (start:Year {value: 2099}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1999}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:ArchaeologicalFacet:Facet {unique_id: 'ARCHAEOLOGICALFACET_ARCHAEOLOGICAL'}) SET f.label = 'archaeological' MERGE (p)-[:HAS_ARCHAEOLOGICAL_FACET]->(f) MERGE (f1:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f1.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f1) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q11767>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q630276>'}) SET p.label = 'Ancient China' SET p.start_year = 1800 SET p.end_year = 220 MERGE (start:Year {value: 1800}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 220}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q29520>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q206715>'}) SET p.label = 'Second Intermediate Period of Egypt' SET p.start_year = 1781 SET p.end_year = 1569 MERGE (start:Year {value: 1781}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1569}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q11768>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q4879010>'}) SET p.label = 'Bedd Branwen Period' SET p.start_year = 1649 SET p.end_year = 1399 MERGE (start:Year {value: 1649}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1399}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q23666>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q1056845>'}) SET p.label = 'Iron Age India' SET p.start_year = 1499 SET p.end_year = 199 MERGE (start:Year {value: 1499}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 199}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q60140>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q455151>'}) SET p.label = 'Amarna Period' SET p.start_year = 1345 SET p.end_year = 1335 MERGE (start:Year {value: 1345}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1335}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q5736>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q486761>'}) SET p.label = 'classical antiquity' SET p.start_year = 1198 SET p.end_year = 500 MERGE (start:Year {value: 1198}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 500}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:ArtisticFacet:Facet {unique_id: 'ARTISTICFACET_ARTISTIC'}) SET f.label = 'artistic' MERGE (p)-[:HAS_ARTISTIC_FACET]->(f) MERGE (f1:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f1.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f1) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q11772>'}) MERGE (p)-[:LOCATED_IN]->(geo) MERGE (geo1:Place {qid: '<http://www.wikidata.org/entity/Q1747689>'}) MERGE (p)-[:LOCATED_IN]->(geo1);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q2299963>'}) SET p.label = 'Woodland period' SET p.start_year = 999 SET p.end_year = 1000 MERGE (start:Year {value: 999}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1000}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q49>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q12793702>'}) SET p.label = 'Classics' SET p.start_year = 999 SET p.end_year = 199 MERGE (start:Year {value: 999}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 199}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q46>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q185047>'}) SET p.label = 'Spring and Autumn period' SET p.start_year = 770 SET p.end_year = 475 MERGE (start:Year {value: 770}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 475}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q29520>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q201038>'}) SET p.label = 'Roman Kingdom' SET p.start_year = 752 SET p.end_year = 508 MERGE (start:Year {value: 752}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 508}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (f1:PoliticalFacet:Facet {unique_id: 'POLITICALFACET_POLITICAL'}) SET f1.label = 'political' MERGE (p)-[:HAS_POLITICAL_FACET]->(f1) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q1048669>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q2911414>'}) SET p.label = 'Second Temple period' SET p.start_year = 529 SET p.end_year = 70 MERGE (start:Year {value: 529}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 70}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q155321>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q843745>'}) SET p.label = 'Classical Greece' SET p.start_year = 489 SET p.end_year = 322 MERGE (start:Year {value: 489}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 322}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:ArchaeologicalFacet:Facet {unique_id: 'ARCHAEOLOGICALFACET_ARCHAEOLOGICAL'}) SET f.label = 'archaeological' MERGE (p)-[:HAS_ARCHAEOLOGICAL_FACET]->(f) MERGE (f1:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f1.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f1) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q11772>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q2000977>'}) SET p.label = 'Fifth-century Athens' SET p.start_year = 479 SET p.end_year = 403 MERGE (start:Year {value: 479}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 403}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q844930>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q11797081>'}) SET p.label = 'La Tène period' SET p.start_year = 449 SET p.end_year = 100 MERGE (start:Year {value: 449}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 100}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:ArchaeologicalFacet:Facet {unique_id: 'ARCHAEOLOGICALFACET_ARCHAEOLOGICAL'}) SET f.label = 'archaeological' MERGE (p)-[:HAS_ARCHAEOLOGICAL_FACET]->(f) MERGE (f1:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f1.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f1) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q27496>'}) MERGE (p)-[:LOCATED_IN]->(geo) MERGE (geo1:Place {qid: '<http://www.wikidata.org/entity/Q27509>'}) MERGE (p)-[:LOCATED_IN]->(geo1);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q12880607>'}) SET p.label = 'Macedonian Period' SET p.start_year = 358 SET p.end_year = 333 MERGE (start:Year {value: 358}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 333}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q11772>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q15843470>'}) SET p.label = 'Roman Palestine' SET p.start_year = 63 SET p.end_year = 324 MERGE (start:Year {value: 63}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 324}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q7570085>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q126949584>'}) SET p.label = 'Gallo-Roman Brussels' SET p.start_year = 56 SET p.end_year = 486 MERGE (start:Year {value: 56}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 486}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q111901161>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q165292>'}) SET p.label = 'Three Kingdoms of Korea' SET p.start_year = 17 SET p.end_year = 660 MERGE (start:Year {value: 17}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 660}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q18097>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q3800893>'}) SET p.label = 'Barbarian invasion of the 3rd century' SET p.start_year = 212 SET p.end_year = 305 MERGE (start:Year {value: 212}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 305}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q146924>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q185043>'}) SET p.label = 'Three Kingdoms' SET p.start_year = 220 SET p.end_year = 280 MERGE (start:Year {value: 220}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 280}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q29520>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q329838>'}) SET p.label = 'Crisis of the Third Century' SET p.start_year = 235 SET p.end_year = 284 MERGE (start:Year {value: 235}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 284}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (f1:PoliticalFacet:Facet {unique_id: 'POLITICALFACET_POLITICAL'}) SET f1.label = 'political' MERGE (p)-[:HAS_POLITICAL_FACET]->(f1) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q2277>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q683551>'}) SET p.label = 'Sixteen Kingdoms' SET p.start_year = 304 SET p.end_year = 439 MERGE (start:Year {value: 304}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 439}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q29520>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q15140974>'}) SET p.label = 'Barbarian invasions of the 4rd century' SET p.start_year = 305 SET p.end_year = 378 MERGE (start:Year {value: 305}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 378}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q17374397>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q11802354>'}) SET p.label = 'Holy Land during Byzantine rule' SET p.start_year = 350 SET p.end_year = 650 MERGE (start:Year {value: 350}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 650}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q7570085>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q126951002>'}) SET p.label = 'Merovingian Brussels' SET p.start_year = 486 SET p.end_year = 751 MERGE (start:Year {value: 486}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 751}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q111901161>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q126951135>'}) SET p.label = 'Carolingian Brussels' SET p.start_year = 486 SET p.end_year = 855 MERGE (start:Year {value: 486}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 855}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q111901161>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q202763>'}) SET p.label = 'Early Middle Ages' SET p.start_year = 500 SET p.end_year = 900 MERGE (start:Year {value: 500}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 900}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q46>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q726805>'}) SET p.label = 'Jahiliyyah' SET p.start_year = 500 SET p.end_year = 700 MERGE (start:Year {value: 500}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 700}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q169977>'}) MERGE (p)-[:LOCATED_IN]->(geo) MERGE (geo1:Place {qid: '<http://www.wikidata.org/entity/Q208154>'}) MERGE (p)-[:LOCATED_IN]->(geo1);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q63226529>'}) SET p.label = 'Early Middle Ages in the Iberian Peninsula' SET p.start_year = 500 SET p.end_year = 1100 MERGE (start:Year {value: 500}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1100}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q12837>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q131433113>'}) SET p.label = 'Qutux Llyung Topa' SET p.start_year = 500 SET p.end_year = 1907 MERGE (start:Year {value: 500}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1907}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:PoliticalFacet:Facet {unique_id: 'POLITICALFACET_POLITICAL'}) SET f.label = 'political' MERGE (p)-[:HAS_POLITICAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q22502>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q132127774>'}) SET p.label = 'Suwawa Kingdom' SET p.start_year = 500 SET p.end_year = 1885 MERGE (start:Year {value: 500}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1885}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:PoliticalFacet:Facet {unique_id: 'POLITICALFACET_POLITICAL'}) SET f.label = 'political' MERGE (p)-[:HAS_POLITICAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q252>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q12057021>'}) SET p.label = 'Medieval India' SET p.start_year = 600 SET p.end_year = 1600 MERGE (start:Year {value: 600}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1600}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q771405>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q131470847>'}) SET p.label = 'anglian' SET p.start_year = 600 SET p.end_year = 900 MERGE (start:Year {value: 600}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 900}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q163>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q4086877>'}) SET p.label = 'Muhammad in Medina' SET p.start_year = 622 SET p.end_year = 632 MERGE (start:Year {value: 622}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 632}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q527887>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q12407080>'}) SET p.label = 'early Islamic period in Palestine' SET p.start_year = 636 SET p.end_year = 1260 MERGE (start:Year {value: 636}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1260}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q7570085>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q4725297>'}) SET p.label = 'Administrative policies of Ali' SET p.start_year = 656 SET p.end_year = 661 MERGE (start:Year {value: 656}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 661}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q27275>'}) MERGE (p)-[:LOCATED_IN]->(geo) MERGE (geo1:Place {qid: '<http://www.wikidata.org/entity/Q27381>'}) MERGE (p)-[:LOCATED_IN]->(geo1);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q702639>'}) SET p.label = 'North South States Period' SET p.start_year = 698 SET p.end_year = 926 MERGE (start:Year {value: 698}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 926}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q18097>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q175801>'}) SET p.label = 'Sican culture' SET p.start_year = 700 SET p.end_year = 1375 MERGE (start:Year {value: 700}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1375}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:ArchaeologicalFacet:Facet {unique_id: 'ARCHAEOLOGICALFACET_ARCHAEOLOGICAL'}) SET f.label = 'archaeological' MERGE (p)-[:HAS_ARCHAEOLOGICAL_FACET]->(f) MERGE (f1:PoliticalFacet:Facet {unique_id: 'POLITICALFACET_POLITICAL'}) SET f1.label = 'political' MERGE (p)-[:HAS_POLITICAL_FACET]->(f1) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q419>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q109368469>'}) SET p.label = 'Five Years'' Wandering' SET p.start_year = 740 SET p.end_year = 745 MERGE (start:Year {value: 740}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 745}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q1155335>'}) MERGE (p)-[:LOCATED_IN]->(geo) MERGE (geo1:Place {qid: '<http://www.wikidata.org/entity/Q262438>'}) MERGE (p)-[:LOCATED_IN]->(geo1) MERGE (geo2:Place {qid: '<http://www.wikidata.org/entity/Q3608523>'}) MERGE (p)-[:LOCATED_IN]->(geo2);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q213649>'}) SET p.label = 'Viking Age' SET p.start_year = 793 SET p.end_year = 1066 MERGE (start:Year {value: 793}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1066}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:ArchaeologicalFacet:Facet {unique_id: 'ARCHAEOLOGICALFACET_ARCHAEOLOGICAL'}) SET f.label = 'archaeological' MERGE (p)-[:HAS_ARCHAEOLOGICAL_FACET]->(f) MERGE (f1:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f1.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f1) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q27479>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q19903299>'}) SET p.label = 'Anglo-Scandinavian' SET p.start_year = 800 SET p.end_year = 1300 MERGE (start:Year {value: 800}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1300}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q38272>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q133871248>'}) SET p.label = 'Medieval Abkhazia' SET p.start_year = 800 SET p.end_year = 1800 MERGE (start:Year {value: 800}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1800}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q31354462>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q123385052>'}) SET p.label = 'Q123385052' SET p.start_year = 800 SET p.end_year = 1000 MERGE (start:Year {value: 800}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1000}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q27496>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q126951168>'}) SET p.label = 'Lotharingian Brussels' SET p.start_year = 855 SET p.end_year = 990 MERGE (start:Year {value: 855}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 990}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q111901161>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q242115>'}) SET p.label = 'Five Dynasties and Ten Kingdoms Period' SET p.start_year = 907 SET p.end_year = 960 MERGE (start:Year {value: 907}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 960}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (f1:PoliticalFacet:Facet {unique_id: 'POLITICALFACET_POLITICAL'}) SET f1.label = 'political' MERGE (p)-[:HAS_POLITICAL_FACET]->(f1) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q29520>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q126951228>'}) SET p.label = 'Reginarid Brussels' SET p.start_year = 990 SET p.end_year = 1406 MERGE (start:Year {value: 990}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1406}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q111901161>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q212685>'}) SET p.label = 'High Middle Ages' SET p.start_year = 1000 SET p.end_year = 1300 MERGE (start:Year {value: 1000}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1300}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q46>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q105605371>'}) SET p.label = 'Shi''a Century' SET p.start_year = 1000 SET p.end_year = 1100 MERGE (start:Year {value: 1000}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1100}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q779924>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q3118827>'}) SET p.label = 'Sperada' SET p.start_year = 1100 SET p.end_year = 1900 MERGE (start:Year {value: 1100}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1900}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q16199>'}) MERGE (p)-[:LOCATED_IN]->(geo) MERGE (geo1:Place {qid: '<http://www.wikidata.org/entity/Q42265>'}) MERGE (p)-[:LOCATED_IN]->(geo1) MERGE (geo2:Place {qid: '<http://www.wikidata.org/entity/Q42776>'}) MERGE (p)-[:LOCATED_IN]->(geo2) MERGE (geo3:Place {qid: '<http://www.wikidata.org/entity/Q42935>'}) MERGE (p)-[:LOCATED_IN]->(geo3) MERGE (geo4:Place {qid: '<http://www.wikidata.org/entity/Q42942>'}) MERGE (p)-[:LOCATED_IN]->(geo4) MERGE (geo5:Place {qid: '<http://www.wikidata.org/entity/Q6237>'}) MERGE (p)-[:LOCATED_IN]->(geo5);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q979160>'}) SET p.label = 'Proto-Renaissance' SET p.start_year = 1100 SET p.end_year = 1200 MERGE (start:Year {value: 1100}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1200}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:ArtisticFacet:Facet {unique_id: 'ARTISTICFACET_ARTISTIC'}) SET f.label = 'artistic' MERGE (p)-[:HAS_ARTISTIC_FACET]->(f) MERGE (f1:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f1.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f1) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q38>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q67587307>'}) SET p.label = 'age of the Communes' SET p.start_year = 1100 SET p.end_year = 1400 MERGE (start:Year {value: 1100}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1400}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q27496>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q1197995>'}) SET p.label = 'Frankokratia' SET p.start_year = 1204 SET p.end_year = 1453 MERGE (start:Year {value: 1204}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1453}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q190600>'}) MERGE (p)-[:LOCATED_IN]->(geo) MERGE (geo1:Place {qid: '<http://www.wikidata.org/entity/Q41>'}) MERGE (p)-[:LOCATED_IN]->(geo1) MERGE (geo2:Place {qid: '<http://www.wikidata.org/entity/Q78967>'}) MERGE (p)-[:LOCATED_IN]->(geo2);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q12407079>'}) SET p.label = 'Mamluk Palestine' SET p.start_year = 1260 SET p.end_year = 1517 MERGE (start:Year {value: 1260}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1517}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q7570085>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q212976>'}) SET p.label = 'Late Middle Ages' SET p.start_year = 1301 SET p.end_year = 1492 MERGE (start:Year {value: 1301}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1492}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q46>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q55525>'}) SET p.label = 'Sanzan period' SET p.start_year = 1322 SET p.end_year = 1429 MERGE (start:Year {value: 1322}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1429}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q15899665>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q127237209>'}) SET p.label = 'Q127237209' SET p.start_year = 1330 SET p.end_year = 1863 MERGE (start:Year {value: 1330}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1863}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:PoliticalFacet:Facet {unique_id: 'POLITICALFACET_POLITICAL'}) SET f.label = 'political' MERGE (p)-[:HAS_POLITICAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q252>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q157109>'}) SET p.label = 'Burgundian Netherlands' SET p.start_year = 1384 SET p.end_year = 1482 MERGE (start:Year {value: 1384}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1482}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (f1:PoliticalFacet:Facet {unique_id: 'POLITICALFACET_POLITICAL'}) SET f1.label = 'political' MERGE (p)-[:HAS_POLITICAL_FACET]->(f1) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q476033>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q126949104>'}) SET p.label = 'Burgundian Brussels' SET p.start_year = 1406 SET p.end_year = 1482 MERGE (start:Year {value: 1406}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1482}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q111901161>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q123135826>'}) SET p.label = 'al-Muammar' SET p.start_year = 1446 SET p.end_year = 1760 MERGE (start:Year {value: 1446}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1760}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:PoliticalFacet:Facet {unique_id: 'POLITICALFACET_POLITICAL'}) SET f.label = 'political' MERGE (p)-[:HAS_POLITICAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q208154>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q125659289>'}) SET p.label = 'Bolango Sultanate' SET p.start_year = 1482 SET p.end_year = 1862 MERGE (start:Year {value: 1482}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1862}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:PoliticalFacet:Facet {unique_id: 'POLITICALFACET_POLITICAL'}) SET f.label = 'political' MERGE (p)-[:HAS_POLITICAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q252>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q126949076>'}) SET p.label = 'Habsburg Brussels' SET p.start_year = 1482 SET p.end_year = 1556 MERGE (start:Year {value: 1482}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1556}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q111901161>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q7851298>'}) SET p.label = 'Tudor London' SET p.start_year = 1509 SET p.end_year = 1603 MERGE (start:Year {value: 1509}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1603}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q84>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q135668179>'}) SET p.label = 'English Tournai' SET p.start_year = 1513 SET p.end_year = 1519 MERGE (start:Year {value: 1513}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1519}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q51462855>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q2909425>'}) SET p.label = 'Ottoman Palestine' SET p.start_year = 1516 SET p.end_year = 1917 MERGE (start:Year {value: 1516}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1917}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q7570085>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q3076765>'}) SET p.label = 'Ottoman Syria' SET p.start_year = 1516 SET p.end_year = 1918 MERGE (start:Year {value: 1516}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1918}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q13415123>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q6262238>'}) SET p.label = 'Jerusalem during the Ottoman period' SET p.start_year = 1517 SET p.end_year = 1917 MERGE (start:Year {value: 1517}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1917}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q1218>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q214078>'}) SET p.label = 'Scientific Revolution' SET p.start_year = 1543 SET p.end_year = 1687 MERGE (start:Year {value: 1543}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1687}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q46>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q661566>'}) SET p.label = 'Dutch Golden Age' SET p.start_year = 1575 SET p.end_year = 1675 MERGE (start:Year {value: 1575}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1675}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q55>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q135222067>'}) SET p.label = 'Republican Brussels' SET p.start_year = 1576 SET p.end_year = 1585 MERGE (start:Year {value: 1576}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1585}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q111901161>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q37853>'}) SET p.label = 'Baroque' SET p.start_year = 1590 SET p.end_year = 1750 MERGE (start:Year {value: 1590}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1750}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:ArtisticFacet:Facet {unique_id: 'ARTISTICFACET_ARTISTIC'}) SET f.label = 'artistic' MERGE (p)-[:HAS_ARTISTIC_FACET]->(f) MERGE (f1:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f1.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f1) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q127834>'}) MERGE (p)-[:LOCATED_IN]->(geo) MERGE (geo1:Place {qid: '<http://www.wikidata.org/entity/Q159>'}) MERGE (p)-[:LOCATED_IN]->(geo1) MERGE (geo2:Place {qid: '<http://www.wikidata.org/entity/Q46>'}) MERGE (p)-[:LOCATED_IN]->(geo2);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q7626770>'}) SET p.label = 'Stuart London' SET p.start_year = 1603 SET p.end_year = 1714 MERGE (start:Year {value: 1603}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1714}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q84>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q2470611>'}) SET p.label = 'The Ruin' SET p.start_year = 1657 SET p.end_year = 1687 MERGE (start:Year {value: 1657}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1687}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q212>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q98872447>'}) SET p.label = 'Kangxi dynastic style' SET p.start_year = 1661 SET p.end_year = 1722 MERGE (start:Year {value: 1661}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1722}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q148>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q120239797>'}) SET p.label = 'Q120239797' SET p.start_year = 1680 SET p.end_year = 1745 MERGE (start:Year {value: 1680}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1745}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:PoliticalFacet:Facet {unique_id: 'POLITICALFACET_POLITICAL'}) SET f.label = 'political' MERGE (p)-[:HAS_POLITICAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q11708>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q127232909>'}) SET p.label = 'Angevin Brussels' SET p.start_year = 1700 SET p.end_year = 1706 MERGE (start:Year {value: 1700}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1706}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q111901161>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q111585844>'}) SET p.label = 'Lustro Real' SET p.start_year = 1729 SET p.end_year = 1733 MERGE (start:Year {value: 1729}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1733}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q8717>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q127240677>'}) SET p.label = 'Theresian Brussels' SET p.start_year = 1740 SET p.end_year = 1780 MERGE (start:Year {value: 1740}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1780}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q111901161>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q120088504>'}) SET p.label = 'Meliau Kingdom' SET p.start_year = 1762 SET p.end_year = 1960 MERGE (start:Year {value: 1762}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1960}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:PoliticalFacet:Facet {unique_id: 'POLITICALFACET_POLITICAL'}) SET f.label = 'political' MERGE (p)-[:HAS_POLITICAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q36117>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q131322075>'}) SET p.label = 'Q131322075' SET p.start_year = 1767 SET p.end_year = 1771 MERGE (start:Year {value: 1767}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1771}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (f1:PoliticalFacet:Facet {unique_id: 'POLITICALFACET_POLITICAL'}) SET f1.label = 'political' MERGE (p)-[:HAS_POLITICAL_FACET]->(f1) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q261241>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q193547>'}) SET p.label = 'Reign of Terror' SET p.start_year = 1793 SET p.end_year = 1794 MERGE (start:Year {value: 1793}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1794}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q58296>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q474757>'}) SET p.label = 'Thermidorian Reaction' SET p.start_year = 1794 SET p.end_year = 1795 MERGE (start:Year {value: 1794}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1795}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q90>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q126949230>'}) SET p.label = 'French Brussels' SET p.start_year = 1797 SET p.end_year = 1815 MERGE (start:Year {value: 1797}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1815}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q111901161>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q10356223>'}) SET p.label = 'Platine Wars' SET p.start_year = 1810 SET p.end_year = 1870 MERGE (start:Year {value: 1810}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1870}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q2362283>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q7201622>'}) SET p.label = 'Antebellum South' SET p.start_year = 1812 SET p.end_year = 1861 MERGE (start:Year {value: 1812}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1861}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q49042>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q51122>'}) SET p.label = 'Unification of Italy' SET p.start_year = 1815 SET p.end_year = 1871 MERGE (start:Year {value: 1815}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1871}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q38>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q126949309>'}) SET p.label = 'Dutch Brussels' SET p.start_year = 1815 SET p.end_year = 1830 MERGE (start:Year {value: 1815}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1830}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q111901161>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q4916863>'}) SET p.label = 'Birmingham pen trade' SET p.start_year = 1822 SET p.end_year = 1960 MERGE (start:Year {value: 1822}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1960}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q2256>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q4090708>'}) SET p.label = 'Boldino autumn' SET p.start_year = 1830 SET p.end_year = 1830 MERGE (start:Year {value: 1830}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1830}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q4092262>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q330961>'}) SET p.label = 'Tanzimat' SET p.start_year = 1839 SET p.end_year = 1876 MERGE (start:Year {value: 1839}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1876}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q43>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q11047542>'}) SET p.label = 'National Organization (Argentina)' SET p.start_year = 1852 SET p.end_year = 1880 MERGE (start:Year {value: 1852}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1880}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q414>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q28028316>'}) SET p.label = 'The Alfred Nobel Family Archives' SET p.start_year = 1868 SET p.end_year = 1905 MERGE (start:Year {value: 1868}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1905}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q10655119>'}) MERGE (p)-[:LOCATED_IN]->(geo) MERGE (geo1:Place {qid: '<http://www.wikidata.org/entity/Q1724971>'}) MERGE (p)-[:LOCATED_IN]->(geo1) MERGE (geo2:Place {qid: '<http://www.wikidata.org/entity/Q1754>'}) MERGE (p)-[:LOCATED_IN]->(geo2) MERGE (geo3:Place {qid: '<http://www.wikidata.org/entity/Q2167>'}) MERGE (p)-[:LOCATED_IN]->(geo3) MERGE (geo4:Place {qid: '<http://www.wikidata.org/entity/Q7308998>'}) MERGE (p)-[:LOCATED_IN]->(geo4);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q531510>'}) SET p.label = 'European Civil War' SET p.start_year = 1870 SET p.end_year = 1945 MERGE (start:Year {value: 1870}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1945}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q46>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q3545916>'}) SET p.label = 'First Constitutional Era' SET p.start_year = 1876 SET p.end_year = 1878 MERGE (start:Year {value: 1876}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1878}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q12560>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q127610143>'}) SET p.label = 'Sultanate of Cal Miskaad' SET p.start_year = 1886 SET p.end_year = 1929 MERGE (start:Year {value: 1886}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1929}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:PoliticalFacet:Facet {unique_id: 'POLITICALFACET_POLITICAL'}) SET f.label = 'political' MERGE (p)-[:HAS_POLITICAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q40556>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q3073537>'}) SET p.label = 'American Century' SET p.start_year = 1898 SET p.end_year = 2000 MERGE (start:Year {value: 1898}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 2000}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q30>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q111699632>'}) SET p.label = 'Black Week' SET p.start_year = 1899 SET p.end_year = 1899 MERGE (start:Year {value: 1899}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1899}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q1010624>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q6262122>'}) SET p.label = 'Jerusalem during the British Mandate of Palestine' SET p.start_year = 1920 SET p.end_year = 1948 MERGE (start:Year {value: 1920}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1948}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q1218>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q3128892>'}) SET p.label = 'Maximato' SET p.start_year = 1928 SET p.end_year = 1934 MERGE (start:Year {value: 1928}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1934}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q96>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q3408764>'}) SET p.label = 'Pre-Code Hollywood' SET p.start_year = 1930 SET p.end_year = 1934 MERGE (start:Year {value: 1930}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1934}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:ArtisticFacet:Facet {unique_id: 'ARTISTICFACET_ARTISTIC'}) SET f.label = 'artistic' MERGE (p)-[:HAS_ARTISTIC_FACET]->(f) MERGE (f1:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f1.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f1) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q34006>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q131673464>'}) SET p.label = 'Golden Age of Argentine cinema' SET p.start_year = 1933 SET p.end_year = 1956 MERGE (start:Year {value: 1933}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1956}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q414>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q113206337>'}) SET p.label = 'Q113206337' SET p.start_year = 1934 SET p.end_year = 1951 MERGE (start:Year {value: 1934}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1951}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q397422>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q136564674>'}) SET p.label = 'Stalin–Beria Terror in Abkhazia' SET p.start_year = 1937 SET p.end_year = 1953 MERGE (start:Year {value: 1937}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1953}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q307022>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q190882>'}) SET p.label = 'Phoney War' SET p.start_year = 1939 SET p.end_year = 1958 MERGE (start:Year {value: 1939}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1958}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q154504>'}) MERGE (p)-[:LOCATED_IN]->(geo) MERGE (geo1:Place {qid: '<http://www.wikidata.org/entity/Q162746>'}) MERGE (p)-[:LOCATED_IN]->(geo1);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q133808358>'}) SET p.label = 'The Soviet era (Lithuania)' SET p.start_year = 1944 SET p.end_year = 1990 MERGE (start:Year {value: 1944}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1990}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q37>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q8683>'}) SET p.label = 'Cold War' SET p.start_year = 1945 SET p.end_year = 1991 MERGE (start:Year {value: 1945}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1991}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q12585>'}) MERGE (p)-[:LOCATED_IN]->(geo) MERGE (geo1:Place {qid: '<http://www.wikidata.org/entity/Q15>'}) MERGE (p)-[:LOCATED_IN]->(geo1) MERGE (geo2:Place {qid: '<http://www.wikidata.org/entity/Q46>'}) MERGE (p)-[:LOCATED_IN]->(geo2) MERGE (geo3:Place {qid: '<http://www.wikidata.org/entity/Q48>'}) MERGE (p)-[:LOCATED_IN]->(geo3);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q104850170>'}) SET p.label = 'Postwar Britain' SET p.start_year = 1945 SET p.end_year = 1979 MERGE (start:Year {value: 1945}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1979}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q145>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q4850939>'}) SET p.label = 'Years of Lead' SET p.start_year = 1969 SET p.end_year = 1982 MERGE (start:Year {value: 1969}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 1982}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q38>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q23019825>'}) SET p.label = 'Rehnquist Court' SET p.start_year = 1986 SET p.end_year = 2005 MERGE (start:Year {value: 1986}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 2005}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q1579670>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q112742065>'}) SET p.label = 'History of Crimea (1991–2014)' SET p.start_year = 1991 SET p.end_year = 2014 MERGE (start:Year {value: 1991}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 2014}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q15966495>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q111601268>'}) SET p.label = 'Mayoralty of Dimitris Avramopoulos' SET p.start_year = 1995 SET p.end_year = 2002 MERGE (start:Year {value: 1995}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 2002}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q1524>'}) MERGE (p)-[:LOCATED_IN]->(geo);

MERGE (p:Period {qid: '<http://www.wikidata.org/entity/Q107124778>'}) SET p.label = 'Q107124778' SET p.start_year = 2017 SET p.end_year = 2021 MERGE (start:Year {value: 2017}) MERGE (p)-[:STARTS_IN]->(start) MERGE (end:Year {value: 2021}) MERGE (p)-[:ENDS_IN]->(end) MERGE (f:CulturalFacet:Facet {unique_id: 'CULTURALFACET_CULTURAL'}) SET f.label = 'cultural' MERGE (p)-[:HAS_CULTURAL_FACET]->(f) MERGE (geo:Place {qid: '<http://www.wikidata.org/entity/Q106592020>'}) MERGE (p)-[:LOCATED_IN]->(geo);
