#!/usr/bin/env python3
"""
Generate Cypher write script and review table from SubjectConcept FAST resolution.

Input: JSON with [{qid, label, fast_id, confidence, fast_heading?}]
  - confidence: HIGH | MEDIUM | REVIEW
Output:
  - scripts/neo4j/write_subject_concept_fast_ids.cypher
  - output/FAST_RESOLUTION_REVIEW.md (MEDIUM items only)

Usage:
    python scripts/backbone/subject/generate_fast_write_script.py [--input path/to/resolution.json]
"""

import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_INPUT = PROJECT_ROOT / "output" / "subject_concepts" / "subject_concept_fast_resolution.json"
CYPHER_OUTPUT = PROJECT_ROOT / "scripts" / "neo4j" / "write_subject_concept_fast_ids.cypher"
REVIEW_OUTPUT = PROJECT_ROOT / "output" / "FAST_RESOLUTION_REVIEW.md"


def load_resolution(path: Path) -> list[dict]:
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, list):
        raise ValueError("Input must be JSON array")
    return data


def validate_row(row: dict, i: int) -> None:
    for key in ("qid", "label", "fast_id", "confidence"):
        if key not in row:
            raise ValueError(f"Row {i}: missing required {key}")

    conf = str(row["confidence"]).upper()
    if conf not in ("HIGH", "MEDIUM", "REVIEW"):
        raise ValueError(f"Row {i}: confidence must be HIGH, MEDIUM, or REVIEW; got {row['confidence']}")


def generate_cypher(rows: list[dict]) -> str:
    lines = [
        "// ============================================================================",
        "// WRITE FAST IDs TO 61 SUBJECTCONCEPTS",
        "// ============================================================================",
        "// Generated by scripts/backbone/subject/generate_fast_write_script.py",
        "// Usage: python scripts/neo4j/run_cypher_file.py scripts/neo4j/write_subject_concept_fast_ids.cypher",
        "// ============================================================================",
        "",
    ]
    for row in rows:
        qid = row["qid"]
        fast_id = row["fast_id"]
        label = row.get("label", "").replace("'", "\\'")
        lines.append(f"// {qid}: {label}")
        lines.append(f"MATCH (sc:SubjectConcept {{qid: '{qid}'}})")
        lines.append(f"SET sc.fast_id = '{fast_id}';")
        lines.append("")
    return "\n".join(lines)


def generate_review_md(rows: list[dict]) -> str:
    medium = [r for r in rows if str(r.get("confidence", "")).upper() == "MEDIUM"]
    if not medium:
        return (
            "# FAST Resolution Review — MEDIUM Items\n\n"
            "**No MEDIUM-confidence items.** All 61 resolved with HIGH confidence.\n"
        )

    lines = [
        "# FAST Resolution Review — MEDIUM Items",
        "",
        "**Purpose:** Manual verification recommended before running the write script.",
        "",
        "| # | QID | Label | FAST ID | FAST Heading | Notes |",
        "|---|-----|-------|---------|--------------|------|",
    ]
    for i, row in enumerate(medium, 1):
        qid = row["qid"]
        label = row.get("label", "").replace("|", "\\|")
        fast_id = row.get("fast_id", "")
        heading = row.get("fast_heading", "").replace("|", "\\|")
        notes = row.get("notes", "").replace("|", "\\|")
        lines.append(f"| {i} | {qid} | {label} | {fast_id} | {heading} | {notes} |")
    lines.extend(["", "---", ""])
    return "\n".join(lines)


def main() -> int:
    input_path = DEFAULT_INPUT
    if "--input" in sys.argv:
        idx = sys.argv.index("--input")
        if idx + 1 < len(sys.argv):
            input_path = Path(sys.argv[idx + 1])

    if not input_path.exists():
        print(f"ERROR: Input file not found: {input_path}")
        print("Create it from subject_concept_anchors_qid_canonical.json + FAST resolution.")
        print("Expected format: [{qid, label, fast_id, confidence, fast_heading?, notes?}]")
        return 1

    rows = load_resolution(input_path)
    for i, row in enumerate(rows):
        validate_row(row, i)

    print(f"Loaded {len(rows)} rows: {sum(1 for r in rows if str(r.get('confidence','')).upper()=='HIGH')} HIGH, "
          f"{sum(1 for r in rows if str(r.get('confidence','')).upper()=='MEDIUM')} MEDIUM, "
          f"{sum(1 for r in rows if str(r.get('confidence','')).upper()=='REVIEW')} REVIEW")

    cypher = generate_cypher(rows)
    CYPHER_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    CYPHER_OUTPUT.write_text(cypher, encoding="utf-8")
    print(f"Wrote: {CYPHER_OUTPUT}")

    review = generate_review_md(rows)
    REVIEW_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    REVIEW_OUTPUT.write_text(review, encoding="utf-8")
    print(f"Wrote: {REVIEW_OUTPUT}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
